version: '3.8'

services:
  fastapi-service:
    image: fastapi-llava-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: always
